@props(['filters', 'categories', 'makes', 'models', 'bodyTypes', 'transmissions', 'fuels', 'prefix' => 'inventory', 'mobile' => false])

@php($value = fn (string $key, mixed $default = '') => old($key, $filters[$key] ?? $default))

<form action="{{ route('cars.index') }}" method="GET" {{ $attributes->merge(['class' => 'grid gap-5']) }} data-inventory-filter-form>
    <div><label class="field-label" for="{{ $prefix }}-q">Keyword</label><input id="{{ $prefix }}-q" name="q" type="search" value="{{ $value('q') }}" class="field-control" placeholder="Make, model, year or stock number"></div>
    <div><label class="field-label" for="{{ $prefix }}-category">Listing category</label><select id="{{ $prefix }}-category" name="listing_category" class="field-control"><option value="">All categories</option>@foreach ($categories as $category)<option value="{{ $category->value }}" @selected($value('listing_category') === $category->value)>{{ $category->label() }}</option>@endforeach</select></div>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
        <div><label class="field-label" for="{{ $prefix }}-make">Make</label><select id="{{ $prefix }}-make" name="make" class="field-control" data-inventory-make><option value="">All makes</option>@foreach ($makes as $make)<option value="{{ $make }}" @selected($value('make') === $make)>{{ $make }}</option>@endforeach</select></div>
        <div><label class="field-label" for="{{ $prefix }}-model">Model</label><select id="{{ $prefix }}-model" name="model" class="field-control" data-inventory-model><option value="">All models</option>@foreach ($models as $model)<option value="{{ $model->model }}" data-make="{{ $model->make }}" @selected($value('model') === $model->model)>{{ $model->model }}</option>@endforeach</select></div>
    </div>
    <div><label class="field-label" for="{{ $prefix }}-body">Body type</label><select id="{{ $prefix }}-body" name="body_type" class="field-control"><option value="">All body types</option>@foreach ($bodyTypes as $bodyType)<option value="{{ $bodyType }}" @selected($value('body_type') === $bodyType)>{{ $bodyType }}</option>@endforeach</select></div>
    <fieldset><legend class="field-label">Year</legend><div class="grid grid-cols-2 gap-3"><input name="year_min" type="number" min="1900" max="{{ now()->year + 1 }}" value="{{ $value('year_min') }}" class="field-control" placeholder="From"><input name="year_max" type="number" min="1900" max="{{ now()->year + 1 }}" value="{{ $value('year_max') }}" class="field-control" placeholder="To"></div></fieldset>
    <fieldset><legend class="field-label">Price</legend><div class="grid grid-cols-2 gap-3"><input name="price_min" type="number" min="0" step="100000" value="{{ $value('price_min') }}" class="field-control" placeholder="Minimum"><input name="price_max" type="number" min="0" step="100000" value="{{ $value('price_max') }}" class="field-control" placeholder="Maximum"></div></fieldset>
    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">
        <div><label class="field-label" for="{{ $prefix }}-transmission">Transmission</label><select id="{{ $prefix }}-transmission" name="transmission" class="field-control"><option value="">Any</option>@foreach ($transmissions as $item)<option value="{{ $item->value }}" @selected($value('transmission') === $item->value)>{{ $item->label() }}</option>@endforeach</select></div>
        <div><label class="field-label" for="{{ $prefix }}-fuel">Fuel type</label><select id="{{ $prefix }}-fuel" name="fuel_type" class="field-control"><option value="">Any</option>@foreach ($fuels as $item)<option value="{{ $item->value }}" @selected($value('fuel_type') === $item->value)>{{ $item->label() }}</option>@endforeach</select></div>
    </div>
    <div><label class="field-label" for="{{ $prefix }}-availability">Availability</label><select id="{{ $prefix }}-availability" name="availability" class="field-control"><option value="">Available and reserved</option><option value="available" @selected($value('availability') === 'available')>Available</option><option value="reserved" @selected($value('availability') === 'reserved')>Reserved</option></select></div>
    <div class="grid grid-cols-2 gap-3 border-t border-border-default pt-5">@if ($mobile)<button type="button" class="btn-secondary" data-inventory-filter-cancel>Cancel</button>@else<a href="{{ route('cars.index') }}" class="btn-secondary">Clear</a>@endif<button type="submit" class="btn-primary">Apply filters</button></div>
</form>
