<?php

return [
    'currency' => 'NGN',
    'admin' => [
        'name' => env('AUTOMERCY_ADMIN_NAME'),
        'email' => env('AUTOMERCY_ADMIN_EMAIL'),
        'password' => env('AUTOMERCY_ADMIN_PASSWORD'),
    ],
    'notifications' => [
        'enquiry_email' => env('AUTOMERCY_ENQUIRY_EMAIL', env('AUTOMERCY_ADMIN_EMAIL')),
    ],
    'business' => [
        'name' => 'Auto Mercy',
        'legal_name' => 'Auto Mercy of God Nigeria Limited',
        'cac_number' => '7328497',
        'operating_since' => 2023,
        'phone_display' => '08061731673',
        'phone_e164' => '+2348061731673',
        'telephone_url' => 'tel:+2348061731673',
        'whatsapp_url' => 'https://wa.me/2348061731673',
        'email' => 'automercyofgod19@gmail.com',
        'opening_hours_display' => 'Monday-Saturday, 8:00 AM-6:00 PM',
    ],
    'social' => [
        'instagram' => env('AUTOMERCY_INSTAGRAM_URL'),
        'tiktok' => env('AUTOMERCY_TIKTOK_URL'),
        'facebook' => env('AUTOMERCY_FACEBOOK_URL'),
    ],
    'locations' => [
        [
            'name' => 'Iju Road',
            'slug' => 'iju',
            'address' => '9 Moshalashi Alao Street, Oyemukun Bus Stop, Iju Road, Lagos',
            'street_address' => '9 Moshalashi Alao Street, Oyemukun Bus Stop, Iju Road',
            'address_locality' => 'Lagos',
            'address_region' => 'Lagos',
            'map_url' => env('AUTOMERCY_IJU_MAP_URL', 'https://www.google.com/maps/search/?api=1&query=9%20Moshalashi%20Alao%20Street%2C%20Oyemukun%20Bus%20Stop%2C%20Iju%20Road%2C%20Lagos'),
        ],
        [
            'name' => 'Bamboo Plaza',
            'slug' => 'ogunnisi-road',
            'address' => '6/8 Ogunnisi Road, Bamboo Plaza, adjacent Omole Phase 1, Lagos',
            'street_address' => '6/8 Ogunnisi Road, Bamboo Plaza, adjacent Omole Phase 1',
            'address_locality' => 'Lagos',
            'address_region' => 'Lagos',
            'map_url' => env('AUTOMERCY_BAMBOO_MAP_URL', 'https://www.google.com/maps/search/?api=1&query=6%2F8%20Ogunnisi%20Road%2C%20Bamboo%20Plaza%2C%20Lagos'),
        ],
    ],
    'seo' => [
        'base_url' => env('SEO_BASE_URL') ?: env('APP_URL', 'http://localhost'),
        'content_last_modified' => '2026-09-15',
        'landings' => [
            'makes/toyota' => [
                'published' => env('SEO_LANDING_TOYOTA_PUBLISHED', false),
                'filter' => ['make' => 'Toyota'],
                'title' => 'Toyota Cars for Sale in Lagos | Auto Mercy',
                'description' => 'Browse published Toyota cars from Auto Mercy, compare current prices and specifications, and contact our team to arrange an inspection in Lagos.',
                'heading' => 'Toyota cars for sale in Lagos',
                'intro' => 'Explore Toyota vehicles in our shared Auto Mercy inventory. Each listing shows its current availability, price, specifications, and photos.',
                'updated_at' => '2026-09-15',
            ],
            'makes/lexus' => [
                'published' => env('SEO_LANDING_LEXUS_PUBLISHED', false),
                'filter' => ['make' => 'Lexus'],
                'title' => 'Lexus Cars for Sale in Lagos | Auto Mercy',
                'description' => 'Browse published Lexus cars from Auto Mercy, compare current prices and specifications, and contact our team to arrange an inspection in Lagos.',
                'heading' => 'Lexus cars for sale in Lagos',
                'intro' => 'Explore Lexus vehicles in our shared Auto Mercy inventory. Contact the team before visiting so we can confirm availability and the viewing location.',
                'updated_at' => '2026-09-15',
            ],
            'categories/foreign-used' => [
                'published' => env('SEO_LANDING_FOREIGN_USED_PUBLISHED', false),
                'filter' => ['listing_category' => 'foreign_used'],
                'title' => 'Foreign-Used Cars for Sale in Lagos | Auto Mercy',
                'description' => 'Browse currently published foreign-used cars from Auto Mercy with prices, specifications, photos, and direct inspection enquiries.',
                'heading' => 'Foreign-used cars for sale in Lagos',
                'intro' => 'Compare foreign-used vehicles currently published in Auto Mercy’s shared inventory, then contact our team to confirm availability and arrange an inspection.',
                'updated_at' => '2026-09-15',
            ],
            'categories/brand-new' => [
                'published' => env('SEO_LANDING_BRAND_NEW_PUBLISHED', false),
                'filter' => ['listing_category' => 'brand_new'],
                'title' => 'Brand-New Cars for Sale in Lagos | Auto Mercy',
                'description' => 'Browse currently published brand-new cars from Auto Mercy with current prices, specifications, photos, and direct assistance.',
                'heading' => 'Brand-new cars for sale in Lagos',
                'intro' => 'See brand-new vehicles currently published in Auto Mercy’s shared inventory. Every vehicle retains one detail page and one enquiry path.',
                'updated_at' => '2026-09-15',
            ],
            'body-types/suv' => [
                'published' => env('SEO_LANDING_SUV_PUBLISHED', false),
                'filter' => ['body_type' => 'SUV'],
                'title' => 'SUVs for Sale in Lagos | Auto Mercy',
                'description' => 'Browse currently published SUVs from Auto Mercy, compare current prices and specifications, and arrange an inspection in Lagos.',
                'heading' => 'SUVs for sale in Lagos',
                'intro' => 'Compare SUVs in the same shared Auto Mercy inventory used across the website. Contact our team to confirm the viewing location before visiting.',
                'updated_at' => '2026-09-15',
            ],
        ],
    ],
    'analytics' => [
        'provider' => env('ANALYTICS_PROVIDER', 'ga4'),
        'enabled' => env('ANALYTICS_ENABLED', false),
        'measurement_id' => env('ANALYTICS_MEASUREMENT_ID'),
        'requires_consent' => env('ANALYTICS_REQUIRE_CONSENT', true),
    ],
    'reservation' => [
        'amount' => 500_000,
        'duration_days' => 14,
    ],
    'media' => [
        'disk' => env('CAR_MEDIA_DISK', 'public'),
        'image_max_kilobytes' => 15 * 1024,
        'image_max_pixels' => 40_000_000,
        'image_extensions' => ['jpg', 'jpeg', 'png', 'webp'],
        'image_mime_types' => ['image/jpeg', 'image/png', 'image/webp'],
        'original_max_width' => 2400,
        'original_max_height' => 1800,
        'variants' => [
            'thumbnail' => 320,
            'card' => 720,
            'medium' => 1200,
            'large' => 1800,
        ],
        'webp_quality' => 82,
    ],
];
