@php
    $vehicleName = trim(implode(' ', array_filter([$car->year, $car->make?->name, $car->carModel?->name, $car->trim])));
    $messageUrl = $business['whatsapp_url'].'?text='.rawurlencode("Hello Auto Mercy, I am interested in the {$vehicleName} ({$car->stock_number}).");
@endphp
<x-layouts.public-layout :title="$vehicleName.' | Auto Mercy'" :description="Str::limit(strip_tags($car->description), 155)" :canonical="route('cars.show', $car)" :image="$car->primaryImage?->url ?? asset('images/auto-mercy-hero.webp')">
    <div class="bg-surface-secondary py-section-compact"><div class="mx-auto max-w-site px-gutter">
        <nav class="mb-6 text-sm text-text-secondary" aria-label="Breadcrumb"><a href="{{ route('home') }}" class="hover:text-mercy-red">Home</a> <span aria-hidden="true">/</span> <a href="{{ route('cars.index') }}" class="hover:text-mercy-red">Available Cars</a> <span aria-hidden="true">/</span> <span class="text-carbon">{{ $vehicleName }}</span></nav>
        <div class="grid gap-8 lg:grid-cols-[1.45fr_0.75fr]">
            <div><div class="aspect-vehicle-gallery overflow-hidden rounded-card bg-pure-white">@if ($car->primaryImage)<img src="{{ $car->primaryImage->url }}" width="{{ $car->primaryImage->width ?? 1600 }}" height="{{ $car->primaryImage->height ?? 1200 }}" alt="{{ $car->primaryImage->alt_text }}" class="h-full w-full object-cover">@else<img src="{{ asset('images/auto-mercy-hero.webp') }}" width="1792" height="1024" alt="Auto Mercy vehicle image placeholder" class="h-full w-full object-cover">@endif</div><section class="mt-6 rounded-card bg-pure-white p-6 shadow-card"><h2 class="font-display text-3xl">Vehicle details</h2><div class="mt-5 whitespace-pre-line leading-7 text-text-secondary">{{ $car->description }}</div></section></div>
            <aside class="h-fit rounded-card border border-border-default bg-pure-white p-6 shadow-card lg:sticky lg:top-6"><span class="rounded-badge bg-status-available px-3 py-1.5 text-xs font-bold uppercase tracking-label text-pure-white">{{ $car->status->label() }}</span><h1 class="mt-5 font-display text-h3">{{ $vehicleName }}</h1><p class="mt-2 text-sm text-text-secondary">Stock {{ $car->stock_number }}</p><p class="mt-6 text-vehicle-price">₦{{ number_format((float) $car->price_amount) }}</p><dl class="mt-6 grid grid-cols-2 gap-4 border-y border-border-default py-5 text-sm"><div><dt class="text-text-secondary">Mileage</dt><dd class="mt-1 font-semibold">{{ number_format((float) $car->mileage) }} {{ $car->mileage_unit?->value }}</dd></div><div><dt class="text-text-secondary">Transmission</dt><dd class="mt-1 font-semibold">{{ $car->transmission?->label() }}</dd></div><div><dt class="text-text-secondary">Fuel</dt><dd class="mt-1 font-semibold">{{ $car->fuel_type?->label() }}</dd></div><div><dt class="text-text-secondary">Car stand</dt><dd class="mt-1 font-semibold">{{ $car->carStand?->name }}</dd></div></dl><div class="mt-6 grid gap-3"><a href="{{ $messageUrl }}" class="btn-primary" target="_blank" rel="noopener">Ask About This Car</a><a href="{{ $business['telephone_url'] }}" class="btn-secondary">Call {{ $business['phone_display'] }}</a></div></aside>
        </div>
    </div></div>
</x-layouts.public-layout>
